title: "Career Profile"
description: "Software Engineer, Backend Applications Developer, Systems Integrator, Java Engineer"
url: ""
baseurl: ""  # user sites use root

# Use GitHub's official 'Minimal' theme via remote_theme
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme

# Optional site settings that the theme can show
logo: https://raw.githubusercontent.com/mvmags/resources/main/pics/Marco.png   # add when you have one
show_downloads: false
google_analytics: G-DX96TSN3D3
